<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LTPCHE102076955" name="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest" tests="17" failures="6" timestamp="2021-01-03T08:46:27 IST" time="2338.100" errors="0">
  <testcase name="deleteAllData_VaccineLogTest" time="43.245" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyVaccineLogLinkIsDisplayed_VaccineLogPageTest" time="85.298" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyNavigationToVaccineLogPage_VaccineLogPageTest" time="51.705" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyAddMomentSectionIsDisplayed_VaccineLogPageTest" time="57.784" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyNavgationToAddNewMomentScreenFromVaccineLog_VaccineLogPageTest" time="64.158" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyMomentCreationWithImageMilestoneNoteHeightWeight_VaccineLogPageTest" time="184.803" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyBackButton_VaccineLogPageTest" time="62.473" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyEditMomentCardWithoutImage_VaccineLogPageTest" time="136.613" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyDeleteMomentCardWithoutImage_VaccineLogPageTest" time="172.603" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Check if Moment deleted from vaccine log page, Note of deleted moment not to be displayed on vaccine log page expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Check if Moment deleted from vaccine log page, Note of deleted moment not to be displayed on vaccine log page expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest.verifyDeleteMomentCardWithoutImage_VaccineLogPageTest(VaccineLogPageTest.java:455)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyDeleteMomentCardWithoutImage_VaccineLogPageTest -->
  <system-out/>
  <testcase name="verifyMomentShareExternalAppsWithoutImage_VaccineLogPageTest" time="137.958" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Check Messages app is displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Check Messages app is displayed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest.verifyMomentShareExternalAppsWithoutImage_VaccineLogPageTest(VaccineLogPageTest.java:484)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyMomentShareExternalAppsWithoutImage_VaccineLogPageTest -->
  <system-out/>
  <testcase name="verifyMomentWithoutImageShareInGroupChat_VaccineLogPageTest" time="91.583" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyFullPageImageView_VaccineLogPageTest" time="217.786" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyMoreButtonFullPageImageView_VaccineLogPageTestt" time="165.636" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Check if Weight saved in backend expected [47.14] but found [78.24],
	Check if Height saved in backend expected [80.65] but found [77.62],
	Check if Note saved in backend expected [F1EdHWLSTqLgdp997bx7] but found [wLPOjzNurz35cHAR9ucz]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Check if Weight saved in backend expected [47.14] but found [78.24],
Check if Height saved in backend expected [80.65] but found [77.62],
Check if Note saved in backend expected [F1EdHWLSTqLgdp997bx7] but found [wLPOjzNurz35cHAR9ucz]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest.verifyMoreButtonFullPageImageView_VaccineLogPageTestt(VaccineLogPageTest.java:708)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyMoreButtonFullPageImageView_VaccineLogPageTestt -->
  <system-out/>
  <testcase name="verifyCrossBtnFullImageView_VaccineLogPageTest" time="163.416" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Check if Weight saved in backend expected [26.1] but found [78.24],
	Check if Height saved in backend expected [93.15] but found [77.62],
	Check if Note saved in backend expected [5chA4HKbbzRhovSUHrXU] but found [wLPOjzNurz35cHAR9ucz]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Check if Weight saved in backend expected [26.1] but found [78.24],
Check if Height saved in backend expected [93.15] but found [77.62],
Check if Note saved in backend expected [5chA4HKbbzRhovSUHrXU] but found [wLPOjzNurz35cHAR9ucz]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest.verifyCrossBtnFullImageView_VaccineLogPageTest(VaccineLogPageTest.java:772)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCrossBtnFullImageView_VaccineLogPageTest -->
  <system-out/>
  <testcase name="verifyEditMomentFullImageView_VaccineLogPageTest" time="277.620" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest"/>
  <system-out/>
  <testcase name="verifyShareInGroupChatFullImageView_VaccineLogPageTest" time="189.281" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Check if Weight saved in backend expected [19] but found [85.24],
	Check if Height saved in backend expected [65.78] but found [73.7],
	Check if Note saved in backend expected [ZYY5c4kDGO30bAqhOLNv] but found [qG6RbRGMWru4KRspjZxU1234]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Check if Weight saved in backend expected [19] but found [85.24],
Check if Height saved in backend expected [65.78] but found [73.7],
Check if Note saved in backend expected [ZYY5c4kDGO30bAqhOLNv] but found [qG6RbRGMWru4KRspjZxU1234]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest.verifyShareInGroupChatFullImageView_VaccineLogPageTest(VaccineLogPageTest.java:963)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyShareInGroupChatFullImageView_VaccineLogPageTest -->
  <system-out/>
  <testcase name="verifyShareInExternalAppsFullImageView_VaccineLogPageTest" time="236.138" classname="com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Check if Weight saved in backend expected [58.17] but found [85.24],
	Check if Height saved in backend expected [78.82] but found [73.7],
	Check if Note saved in backend expected [2Cl2AFrmnaqu6bnJZhgy] but found [qG6RbRGMWru4KRspjZxU1234],
	Check if Messages app displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Check if Weight saved in backend expected [58.17] but found [85.24],
Check if Height saved in backend expected [78.82] but found [73.7],
Check if Note saved in backend expected [2Cl2AFrmnaqu6bnJZhgy] but found [qG6RbRGMWru4KRspjZxU1234],
Check if Messages app displayed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest.verifyShareInExternalAppsFullImageView_VaccineLogPageTest(VaccineLogPageTest.java:1026)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyShareInExternalAppsFullImageView_VaccineLogPageTest -->
  <system-out/>
</testsuite> <!-- com.pom.crimson.testcases.momentlog.smoke.VaccineLogPageTest -->
